siteConfig:
  title: Saber.js
  description: A framework for building modern static websites.

theme: ./src

markdown:
  highlighter: prism

themeConfig:
  sidebar:
  - title: Guide
    children:
      - title: Introduction
        link: /docs/
      - title: Installation
        link: /docs/installation.html
      - title: Pages
        link: /docs/pages.html
      - title: Permalinks
        link: /docs/permalinks.html
      - title: Layouts
        link: /docs/layouts.html
      - title: Theming
        link: /docs/theming.html
  - title: References
    children:
      - title: Markdown Features
        link: /docs/markdown-features.html
      - title: Saber Config
        link: /docs/saber-config.html
      - title: Saber Browser APIs
        link: /docs/browser-apis.html
      - title: Saber Node APIs
        link: /docs/node-apis.html
      - title: Page Interface
        link: /docs/page-interface.html
