siteConfig:
  title: Saber
  description: A framework for building modern static websites.

theme: ./src

markdown:
  highlighter: prism
  plugins:
  - resolve: markdown-it-footnote

build:
  lazy: true

permalinks:
  post: /blog/:slug.html

themeConfig:
  sidebar:
  - title: Basics
    children:
      - title: Introduction
        link: /docs/
      - title: Installation
        link: /docs/installation.html
      - title: Pages
        link: /docs/pages.html
      - title: Permalinks
        link: /docs/permalinks.html
      - title: Layouts
        link: /docs/layouts.html
      - title: Theming
        link: /docs/theming.html
      - title: Public Folder
        link: /docs/public-folder.html
  - title: References
    children:
      - title: Markdown Features
        link: /docs/markdown-features.html
      - title: Saber Config
        link: /docs/saber-config.html
      - title: Plugin API
        link: /docs/plugin-api.html
      - title: Saber Instance
        link: /docs/saber-instance.html
      - title: Saber Browser APIs
        link: /docs/browser-apis.html
      - title: Saber Node APIs
        link: /docs/node-apis.html
      - title: Page Interface
        link: /docs/page-interface.html

plugins:
  - resolve: ../packages/saber-plugin-google-analytics
    options:
      trackId: UA-54857209-16
  - resolve: ../packages/saber-plugin-query-posts
