siteConfig:
  title: Saber.js
  description: A framework for building modern static websites.

theme: ./src

markdown:
  highlighter: prism

themeConfig:
  sidebar:
  - title: Guide
    children:
      - title: Introduction
        link: /docs/
      - title: Installation
        link: /docs/installation.html
  - title: Content
    children:
      - title: Markdown
        link: /docs/markdown.html
  - title: Site Structure
    children:
      - title: Routing
        link: /docs/routing.html
      - title: Permalinks
        link: /docs/permalinks.html
      - title: Theming
        link: /docs/theming.html
  - title: References
    children:
      - title: Saber Config
        link: /docs/saber-config.html
      - title: Saber Browser APIs
        link: /docs/browser-apis.html
      - title: Page Interface
        link: /docs/page-interface.html
